In [1]:
!pip3 install numpy


[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: pip install --upgrade pip


# import numpy

In [3]:
print("Hello World")

Hello World


In [2]:
import numpy as np

[1,23,4,78,  ,88]

In [4]:
arr= np.array([1,2,3,4,5])

In [7]:
(arr)

array([1, 2, 3, 4, 5])

In [14]:
arr_2d= np.array([[1,2,3,4,5],[44,7,8,9,6]])

In [15]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [44,  7,  8,  9,  6]])

In [16]:
arr.shape

(5,)

In [17]:
arr_2d.shape

(2, 5)

In [19]:
arr_2d.ndim

2

In [23]:
arr_d= np.array([[1,2,3,4,5],[44,7,8,9,6],[8,2,3,4,5],[1,2,3,4,5],[1,2,3,4,5]])

In [26]:
arr_d

array([[ 1,  2,  3,  4,  5],
       [44,  7,  8,  9,  6],
       [ 8,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5]])

In [30]:
arr_3d = np.array([[[1, 2], [3, 4]],[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [32]:
arr_3d.ndim

3

In [36]:
a=12
b=1.2
d=('abcd')

In [38]:
arr.dtype

dtype('int64')

In [ ]:
arr= np.array([1,2,3,4,5])

In [46]:
arr_p = np.array(['a','b','c','d'])

In [47]:
arr_p.dtype

dtype('<U1')

# min max

In [48]:
arr

array([1, 2, 3, 4, 5])

In [52]:
maxvalue= np.max(arr)

In [53]:
maxvalue

5

In [54]:
np.min(arr)

1

In [55]:
np.mean(arr)

3.0

In [56]:
np.median(arr)

3.0

In [58]:
arr.sum()

15

In [62]:
np.std(arr)

1.4142135623730951

In [60]:
arr.std()

1.4142135623730951

In [61]:
arr.var()

2.0

In [65]:
ghan_arr= np.array([654,86,456,45,65,687,87])

In [73]:
ghan_arr= np.arange